version: 2

shared: &shared
    working_directory: /var/www/html
    steps:
        - checkout
        - run: composer self-update
        - run: composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
        - run:
            command: vendor/bin/phpunit
            environment:
                APP_ENV: test

workflows:
    version: 2
    build:
        jobs:
            - php-7.1
            - php-7.1-prefer-lowest

jobs:
    "php-7.1-prefer-lowest":
        <<: *shared
        docker:
            - image: circleci/php:7.1
              environment:
                  COMPOSER_FLAGS: --prefer-lowest
    "php-7.1":
        <<: *shared
        docker:
            - image: circleci/php:7.1
