version: 2

shared: &shared
    working_directory: /var/www/html
    environment:
        APP_ENV: test
        COMPOSER_FLAGS: ''
    steps:
        - checkout
        - run: echo $COMPOSER_FLAGS $APP_ENV
        - run: composer self-update
        - run: composer update $COMPOSER_FLAGS --no-interaction --prefer-source
        - run:
            command: vendor/bin/phpunit
            environment:
                APP_ENV: test


workflows:
    version: 2
    branches:
        ignore:
            - /analysis-.*/
    build:
        jobs:
            - php-7.1
            - php-7.1-prefer-lowest

jobs:
    "php-7.1-prefer-lowest":
        <<: *shared
        environment:
            COMPOSER_FLAGS: --prefer-lowest
        docker:
            - image: circleci/php:7.1
    "php-7.1":
        <<: *shared
        docker:
            - image: circleci/php:7.1
