version: 2
jobs:
    build:
        working_directory: /var/www/html
        docker:
            - image: circleci/php:7.1
              environment:
                  APP_ENV: test
        steps:
            - checkout
            - run: composer self-update
            - run: composer install -n --prefer-dist
            - run:
                  name: Display PHP information
                  command: |
                      php -v
                      composer --version
            - run: vendor/bin/phpunit
