version: 2

shared: &shared
    working_directory: /var/www/html
    environment:
        APP_ENV: test
    steps:
        - checkout
        - run: echo $COMPOSER_FLAGS $APP_ENV
        - run: composer self-update
        - run: composer update $COMPOSER_FLAGS --no-interaction --prefer-source
        - run:
            command: vendor/bin/phpunit

workflows:
    version: 2
    build:
        jobs:
            - php-7.1
            - php-7.1-prefer-lowest
            - php-7.2
            - php-7.2-prefer-lowest
            - php-7.3
            - php-7.3-prefer-lowest

jobs:
    php-7.1-prefer-lowest:
        <<: *shared
        docker:
            - image: circleci/php:7.1
              environment:
                  COMPOSER_FLAGS: --prefer-lowest
    php-7.1:
        <<: *shared
        docker:
            - image: circleci/php:7.1

    php-7.2-prefer-lowest:
        <<: *shared
        docker:
            - image: circleci/php:7.2
              environment:
                  COMPOSER_FLAGS: --prefer-lowest
    php-7.2:
        <<: *shared
        docker:
            - image: circleci/php:7.2

    php-7.3-prefer-lowest:
        <<: *shared
        docker:
            - image: circleci/php:7.3
              environment:
                  COMPOSER_FLAGS: --prefer-lowest
    php-7.3:
        <<: *shared
        docker:
            - image: circleci/php:7.3
